apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-input-param
spec:
  entrypoint: bash-template
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: bash-template
      inputs:
        parameters:
          - name: message
      container:
        image: bash
        command: [ "bash", "-c" ]
        args: [ "echo {{inputs.parameters.message}}" ]
