apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  source:
    path: charts/argo-workflows
    repoURL: https://github.com/argoproj/argo-helm.git
    targetRevision: HEAD
    helm:
      values: |
        server:
          authMode: server
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
